### ISSUE TITLE
Hotel meetups/rideshares

### ISSUE THREAD

**Issue by bboscoe** [si2-urssi/berkeley_workshop#17]
Discussion topic: 
Should we have a page for hotel meetups and rideshares to workshops/ airport logistics?

**Comment by karthik** [comment]
Hi @bboscoe I created a blank Google doc for this here: https://docs.google.com/document/d/1UgJDJuYhEcBkK0XQc-rnzzah_lNFcu4KqQIiSuTSCkE/edit?usp=sharing

Please use that coordinate ride shares. I'll add it to the main readme and also include that in an email to everyone during the event.
