### ISSUE TITLE
Software Usability

### ISSUE THREAD

**Issue by 11fish** [si2-urssi/berkeley_workshop#25]
Discussion topic: software usability
Brief description of issue/challenge:  Software is often released with no consideration of the effort it will take to learn to use it.  A result is a new learning curve each time a practitioner moves to a new package, and that curve may be steeper than it needs to be.  To what extent can interfaces be standardized?   How can we incorporate user testing as part of the development process?
Lead/moderator: 
Links to resources:

**Comment by danielskatz** [comment]
This seems like a good discussion topic - I'm not sure why it was closed...
